spring:
  application:
    name: grad-school-migration-platform

  datasource:
    url: jdbc:postgresql://localhost:5432/migrationdb
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

    open-in-view: false

    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics

  endpoint:
    health:
      show-details: always

app:
  environment: local